export {default as homeIndicatorsPageStore } from "../stores/home-indicators-page-store"
export {default as safetyPageStore} from "../stores/safety-page-store"
export {default as healthPageStore} from "../stores/health-page-store"
export {default as ecologyPageStore} from "../stores/ecology-page-store"
export {default as administrationPageStore} from "../stores/administration-page-store"